### ISSUE TITLE
❓ Should we have an escape hatch to write inline JavaScript.

### ISSUE THREAD

**Issue by pd-andy** [ren-lang/compiler#42]
In previous iterations/explorations, I've always implemented an escape hatch to write JavaScript in sticky situations.

Although I'm generally disinclined to support something like this long-term, it might be a nice stopgap for throwing together things can't be implemented in Ren itself.

**Comment by lpil** [comment]
Can one import JS functions in Ren?

**Comment by pd-andy** [comment]
Oops, just saw this! At the moment ren's imports transpile directly to js imports so yeah you can import js files and packages (if you're running on node) no problem.

In the future I want to add purescript/gleam-style external js files and dedicated syntax for importing those, which renders this issue a bit moot 😅.
