### ISSUE TITLE
🐛 Parentheses aren't stripped during optimisation for function application.

### ISSUE THREAD

**Issue by pd-andy** [ren-lang/compiler#52]
We have an optimisation that can unwrap nested parenthesised expression so something like:
```
(((n - 1)))
```
can unwrap to:
```
(n - 1)
```
For function application, however, we can eliminated the parentheses entirely:
```
foo ((((n - 1))))
```
should become:
```
foo (n - 1)
```
Note that the parentheses here are not for grouping the expression but are how javascript does function application! Currently we don't do the final unwrap and we end up with:
```
foo ((n - 1))
```

**Comment by Alpvax** [comment]
This case also applies to conditions (`if ((n - 1)) { ... }`), and potentially match expressions (I haven't yet looked into their specifics).

However, I think this is a js specific optimisation. If transpiling to something like elm, the parentheses would still be required.
I don't know whether you want to add target-specific optimisation, leave it as-is for now, or just fix it for js and deal with any other targets if/when it causes issues down the line (if any other targets are added).

**Comment by pd-andy** [comment]
I don't think we should worry about platform-specific optimisations only for now, consider ren compile-to-js only. Sorting that out should come later, when we have a better idea of what those platforms are and have a better idea of how to organise the compiler around that.
