### ISSUE TITLE
✨ Transform wildcard expressions `_` into lambdas. 

### ISSUE THREAD

**Issue by pd-andy** [ren-lang/compiler#57]
It'd be very nifty if we could use the wildcard identifier (`_`) as a placeholder in expressions and desugar that to lambda functions at compile time.

## Use-cases:

- **Partial operator application**:

```
Array.map (_ < 10) [5, 10, 15, 20]
```
becomes:
```
Array.map (fun $1 => $1 < 10) [5, 10, 15, 20]
```

---

- **Object field access**:

```
_.foo
```
becomes:
```
fun $1 => $1.foo
```

(This would replace the current field accessor identifier `.foo`. Although that makes this particular scenario slightly more verbose, we gain uniformity and remove a unique piece of compiler magic in place for a single construct used for everything)

---

- **Lambda-case pattern matching**:

```
when _
  is [x, y] => ...
  else => ...
```
becomes:
```
fun $1 =>
  when $1
    is [x, y] => ...
    else => ...
```

---

- **Positional piping**:

```
y |> f x _ z
```
becomes:
```
y |> (fun $1 => f x $1 z)
```

---

## Multiple placeholders:

When multiple placeholders are present in a single expression we should generate a lambda with multiple arguments:

```
let foo = bar a _ c _
```
should become:
```
let foo = fun $1 $2 => bar a $1 c $2
```

**Comment by Alpvax** [comment]
Is it worth thinking about expanding the multiple placeholder version to allow numbered wildcards?
Would allow `foo a _1 c _0` to become `fun $0 $1 => foo a $0 c $1`. Obviously could be 1-based rather than 0-based if desired.

**Comment by pd-andy** [comment]
I think it's best if they are always in order of appearance, keep things consistent. I can see it being a slightly confusing feature (especially if someone leans very heavily into it) and making sure it acts the same everywhere is pretty important I'd say.
